name: Clone
on: [push]
jobs:
  master:
    name: Clone to Oak
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update
        run: |
          git config --global user.email "robots@oakmound.com"
          git config --global user.name "Oak Bot"
          git clone https://github.com/oakmound/oak.wiki.git
          cp ./*.md oak.wiki/
          cd oak.wiki
          git add *
          git commit -m "Push from Github Actions"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WIKI_PUSH_TOKEN }} 
          directory: oak.wiki
          repository: oakmound/oak.wiki